# Generated by Django 6.0.6 on 2026-06-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsdetail',
            old_name='new',
            new_name='news',
        ),
    ]
