# Generated by Django 6.0.6 on 2026-06-22 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userinfo_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrecord',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roots', to='api.commentrecord', verbose_name='根评论'),
        ),
        migrations.AlterField(
            model_name='commentrecord',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='api.commentrecord', verbose_name='回复'),
        ),
    ]
