# Generated by Django 6.0.6 on 2026-06-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_commentrecord_root_alter_commentrecord_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(max_length=64, verbose_name='头像'),
        ),
    ]
